language: cpp
dist: bionic
addons:
  apt:
    update: false
    packages: libboost-test-dev

script:
- cmake .
- cmake --build . --target package

deploy:
  provider: bintray
  file: bintray.json
  user: bergentroll
  cleanup: false
  edge: true
